#!/bin/bash

rm -rf ./dist
docker rm -f jekyll
git submodule update --init --recursive
docker-machine create --driver virtualbox dev
docker-machine start dev
eval "$(docker-machine env dev)"
echo "Visit site at: $(docker-machine ip `docker-machine active`)"